openapi: "3.0.1"
info:
  title: '@project.name@'
  version: '@project.version@'
servers:
  - url: /api
    description: Auto
paths:
  /health:
    get:
      tags:
        - Health
      summary: Check if system is healthy
      description: Check if system is healthy
      operationId: health
      responses:
        200:
          description: Healthy

  /system:
    get:
      tags:
        - System
      summary: Get system properties
      description: Get system properties
      operationId: getSystemProperties
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Properties'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Properties:
      type: object
    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: Http error code
        number:
          type: integer
          format: int32
          description: Código numérico único del error
        code:
          type: string
          description: Código alfanumérico único del error
        title:
          type: string
          description: Http error message
        description:
          type: string
          description: Error description
        data:
          type: object
          properties: {}
          description: Additional data from error
